// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Pedro",
            "email": "pedro@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/produtos": {
            "get": {
                "description": "Retorna uma lista de todos os produtos cadastrados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produtos"
                ],
                "summary": "Lista todos os produtos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Produto"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Cria um novo produto com os dados fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produtos"
                ],
                "summary": "Cria um novo produto",
                "parameters": [
                    {
                        "description": "Dados do produto",
                        "name": "produto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Produto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Produto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/produtos/{id}": {
            "get": {
                "description": "Retorna um produto específico pelo seu ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produtos"
                ],
                "summary": "Obtém um produto por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do produto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Produto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Atualiza um produto existente com os dados fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produtos"
                ],
                "summary": "Atualiza um produto",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do produto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados do produto",
                        "name": "produto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Produto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Produto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove um produto pelo seu ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produtos"
                ],
                "summary": "Remove um produto",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do produto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/relatorios": {
            "get": {
                "description": "Retorna dados gerais do sistema como vendas do dia, total de clientes e produtos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relatorios"
                ],
                "summary": "Obtém relatório geral",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/vendas": {
            "get": {
                "description": "Retorna uma lista de todas as vendas cadastradas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vendas"
                ],
                "summary": "Lista todas as vendas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Venda"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Cria uma nova venda com os dados fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vendas"
                ],
                "summary": "Cria uma nova venda",
                "parameters": [
                    {
                        "description": "Dados da venda",
                        "name": "venda",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateVendaDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Venda"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/vendas/cliente/{cliente}": {
            "get": {
                "description": "Retorna uma lista de vendas filtrada por cliente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vendas"
                ],
                "summary": "Lista vendas por cliente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome do cliente",
                        "name": "cliente",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Venda"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/vendas/periodo/{inicio}/{fim}": {
            "get": {
                "description": "Retorna uma lista de vendas filtrada por período",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vendas"
                ],
                "summary": "Lista vendas por período",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Data inicial (timestamp)",
                        "name": "inicio",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Data final (timestamp)",
                        "name": "fim",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Venda"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/vendas/{id}": {
            "get": {
                "description": "Retorna uma venda específica pelo seu ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vendas"
                ],
                "summary": "Obtém uma venda por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da venda",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Venda"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Atualiza uma venda existente com os dados fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vendas"
                ],
                "summary": "Atualiza uma venda",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da venda",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados da venda",
                        "name": "venda",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Venda"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Venda"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove uma venda pelo seu ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vendas"
                ],
                "summary": "Remove uma venda",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da venda",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.CreateItemVendaDTO": {
            "type": "object",
            "required": [
                "produto_id",
                "quantidade"
            ],
            "properties": {
                "produto_id": {
                    "type": "string"
                },
                "quantidade": {
                    "type": "integer"
                }
            }
        },
        "domain.CreateVendaDTO": {
            "type": "object",
            "required": [
                "cliente",
                "itens"
            ],
            "properties": {
                "cliente": {
                    "type": "string"
                },
                "desconto": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0
                },
                "itens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.CreateItemVendaDTO"
                    }
                }
            }
        },
        "domain.ItemVenda": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "preco_unitario": {
                    "type": "number"
                },
                "produto": {
                    "$ref": "#/definitions/domain.Produto"
                },
                "produto_id": {
                    "type": "string"
                },
                "quantidade": {
                    "type": "integer"
                },
                "venda_id": {
                    "type": "string"
                }
            }
        },
        "domain.Produto": {
            "type": "object",
            "properties": {
                "data_criacao": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imagem_url": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "preco": {
                    "type": "number"
                },
                "quantidade": {
                    "type": "integer"
                }
            }
        },
        "domain.Role": {
            "type": "string",
            "enum": [
                "admin",
                "vendedor",
                "cliente"
            ],
            "x-enum-varnames": [
                "RoleAdmin",
                "RoleVendedor",
                "RoleCliente"
            ]
        },
        "domain.Usuario": {
            "type": "object",
            "properties": {
                "ativo": {
                    "type": "boolean"
                },
                "data_criacao": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/domain.Role"
                }
            }
        },
        "domain.Venda": {
            "type": "object",
            "properties": {
                "cliente": {
                    "$ref": "#/definitions/domain.Usuario"
                },
                "cliente_id": {
                    "type": "string"
                },
                "data_criacao": {
                    "type": "string"
                },
                "data_venda": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ItemVenda"
                    }
                },
                "valor_total": {
                    "type": "number"
                },
                "vendedor": {
                    "$ref": "#/definitions/domain.Usuario"
                },
                "vendedor_id": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Operações relacionadas a produtos",
            "name": "produtos"
        },
        {
            "description": "Operações relacionadas a vendas",
            "name": "vendas"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Sistema de Vendas API",
	Description:      "API para gerenciamento de vendas e produtos",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
